:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - default
  - mailers
:schedule:
  StationsinfoJob:
    cron: '1 * * * * *'   # Runs once per minute
    class: StationJob
